version: '3.1'

services:

  backend:
    build: ./backend
    image: backend-nestjs
    container_name: backend
    restart: unless-stopped
    env_file: .env
    environment:
      - NODE_ENV=production
      - OPENCAGE_API_KEY=$OPENCAGE_API_KEY
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    networks:
      - app-network
    # command: ./wait-for.sh db:27017 -- /home/node/app/node_modules/.bin/nodemon app.js

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
  node_modules:
